name: Auto Update With Quotes

on: push
  #schedule:
    #- cron: "0 * * * *"


permissions: write-all


jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run the quote fetcher
        run: |
          python3 auto_update.py
  
      - name: Commit and push changes
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "New quote generated at $(date +%Y-%m-%d_%H-%M)"
          git push --force
