name: Add Like
on:
  issues:
    types:
      - labeled
jobs:
  add-like:
    env:
      author: ${{github.event.issue.user.login}}
    if: github.event.label.name == 'like'
    runs-on: ubuntu-latest
    name: commit and push like
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Create local changes
      run: |
        #FIND=$(grep -Fx "$author" likers.txt)
        if grep -Fxq "$author" likers.txt
        #if [[! -z "$FIND"]] 
        then
        echo "Try again!"
        else
        echo "$author" >> likers.txt
        #and update counter
        LIKES=$(wc -l < likers.txt);REPLACE=$(echo "<sub><b><i>Like counter: ${LIKES}</i></b></sub>");(head -9 README.md; echo "$REPLACE"; tail -n +11 README.md) > foobar && mv foobar README.md
        fi
    - name: Commit & Push changes
      run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Someone liked on $(date +%Y-%m-%d_%H-%M)"
          git push --force
